apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapdonate-worker-config
  namespace: fiapdonate
data:
  # Hosts do FiapDonateServices (Service Kubernetes no namespace fiapdonate).
  RabbitMq__Host: "rabbitmq"
  RabbitMq__VirtualHost: "/"
  RabbitMq__Username: "fiapdonate"
