apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapdonate-worker
  namespace: fiapdonate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiapdonate-worker
  template:
    metadata:
      labels:
        app: fiapdonate-worker
    spec:
      containers:
        - name: worker
          image: fiapdonateworker:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fiapdonate-worker-config
            - secretRef:
                name: fiapdonate-worker-secrets
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
