apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapdonateworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiapdonateworker
  template:
    metadata:
      labels:
        app: fiapdonateworker
    spec:
      containers:
        - name: worker
          image: fiapdonateworker:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fiapdonateworker-config
            - secretRef:
                name: fiapdonateworker-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
