apiVersion: v1
kind: Secret
metadata:
  name: fiapdonateworker-secret
type: Opaque
stringData:
  RabbitMq__Password: "guest"
  ConnectionStrings__WorkerDb: "Host=postgres;Port=5432;Database=conexao_solidaria;Username=postgres;Password=postgres"
