apiVersion: v1
kind: Service
metadata:
  name: fiapdonate-worker
  namespace: fiapdonate
spec:
  selector:
    app: fiapdonate-worker
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
