// <auto-generated />
using System;
using FiapDonateWorker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiapDonateWorker.Infrastructure.Migrations
{
    [DbContext(typeof(WorkerDbContext))]
    [Migration("20260818024734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiapDonateWorker.Domain.Campanha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorArrecadado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Campanhas", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("FiapDonateWorker.Domain.Doacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataHoraProcessada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataHoraRecebida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCampanha")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDoacao")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Doacoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
